# 常用函数
1. tf.where(条件语句, 真返回A, 假返回B)
2. np.mgrid[] .ravel() np.c_[] 得到网格
3. tf.reduce_mean(tf.square(y_ - y) MSE loss tf.nn.softmax_cross_entropy_with_logits 是softmax+ce
4. l1正则化 l2 正则化 tf.nn.l2_loss(w) tf.reduce_sum(all_regularization) loss = loss_mse + loss_regularization
5. SGD 随机梯度下降 w1.assign_sub(lr * grads) 直接减去梯度乘以学习率
6.

In [2]:
import tensorflow as tf
from sklearn.datasets import load_iris
import os
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
os.environ['CUDA_VISIBLE_DEVICES'] = '1' # 使用 GPU 1
os.environ['TF_FORCE_GPU_ALLOW_GROWTH'] = 'true'

In [3]:
physical_devices = tf.config.list_physical_devices("GPU")
tf.config.experimental.set_memory_growth(physical_devices[0],True)
logical_devices = tf.config.list_logical_devices("GPU")

In [4]:
# tf.where(条件语句, 真返回A, 假返回B)
a = tf.constant([1,2,3,1,1])
b = tf.constant([0,1,3,4,5])
c = tf.where(tf.greater(a,b), a, b) # 若a > b 则返回a 否则返回b
print(c)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [5]:
# np.mgrid[] .ravel() np.c_ 得到网格
x,y = np.mgrid[1:3:1, 2:4:0.5] # 起始值:结束值:步长 左闭右开
print(x)
print(y)

[[1. 1. 1. 1.]
 [2. 2. 2. 2.]]
[[2.  2.5 3.  3.5]
 [2.  2.5 3.  3.5]]


In [7]:
print(x.ravel())
print(y.ravel()) # flatten

[1. 1. 1. 1. 2. 2. 2. 2.]
[2.  2.5 3.  3.5 2.  2.5 3.  3.5]


In [8]:
grid = np.c_[x.ravel(), y.ravel()]
grid

array([[1. , 2. ],
       [1. , 2.5],
       [1. , 3. ],
       [1. , 3.5],
       [2. , 2. ],
       [2. , 2.5],
       [2. , 3. ],
       [2. , 3.5]])

In [13]:
# tf.reduce_mean(tf.square(y_ - y) MSE loss
# tf.nn.softmax_cross_entropy_with_logits 是softmax+ce
rdm = np.random.RandomState(seed=66)
x = rdm.rand(32, 2)
y_ = [[x1 + x2 + (rdm.rand() / 10.0 - 0.05)] for (x1, x2) in x]
x = tf.cast(x, dtype = tf.float32)

w1 = tf.Variable(tf.random.normal([2,1]))

In [15]:
with tf.GradientTape() as tape:
    y = tf.matmul(x, w1)
    loss_mse = tf.reduce_mean(tf.square(y_ - y))

grads = tape.gradient(loss_mse, w1)
print(grads)

tf.Tensor(
[[-0.38845026]
 [-0.16044365]], shape=(2, 1), dtype=float32)


In [ ]:
# l1正则化 l2 正则化 tf.nn.l2_loss(w) tf.reduce_sum(all_regularization) loss = loss_mse + loss_regularization

In [ ]:
# SGD 随机梯度下降 w1.assign_sub(lr * grads)