In [3]:
# 进行鸢尾花分类任务

In [4]:
import tensorflow as tf
from sklearn.datasets import load_iris
import os
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
os.environ['CUDA_VISIBLE_DEVICES'] = '1' # 使用 GPU 1
os.environ['TF_FORCE_GPU_ALLOW_GROWTH'] = 'true'

In [5]:
# gpus = tf.config.experimental.list_physical_devices('GPU')
# if gpus:
#   try:
#     tf.config.experimental.set_virtual_device_configuration(
#         gpus[0],[tf.config.experimental.VirtualDeviceConfiguration(memory_limit=5120)])
#   except RuntimeError as e:
#     print(e)
physical_devices = tf.config.list_physical_devices("GPU")
tf.config.experimental.set_memory_growth(physical_devices[0],True)
logical_devices = tf.config.list_logical_devices("GPU")

In [6]:
# 载入数据
x_data = load_iris().data
y_data = load_iris().target

In [7]:
print('x_shape: ', x_data.shape)
print('y_shape: ', y_data.shape)

x_shape:  (150, 4)
y_shape:  (150,)


In [8]:
data_pd = pd.DataFrame(x_data, columns=[['feature1', 'feature2', 'feature3', 'feature4']])
data_pd['label'] = y_data
data_pd.head()

feature1 feature2 feature3 feature4 label
0      5.1      3.5      1.4      0.2     0
1      4.9      3.0      1.4      0.2     0
2      4.7      3.2      1.3      0.2     0
3      4.6      3.1      1.5      0.2     0
4      5.0      3.6      1.4      0.2     0

In [9]:
data_pd.describe()

feature1    feature2    feature3    feature4       label
count  150.000000  150.000000  150.000000  150.000000  150.000000
mean     5.843333    3.057333    3.758000    1.199333    1.000000
std      0.828066    0.435866    1.765298    0.762238    0.819232
min      4.300000    2.000000    1.000000    0.100000    0.000000
25%      5.100000    2.800000    1.600000    0.300000    0.000000
50%      5.800000    3.000000    4.350000    1.300000    1.000000
75%      6.400000    3.300000    5.100000    1.800000    2.000000
max      7.900000    4.400000    6.900000    2.500000    2.000000

In [10]:
# 数据集乱序
np.random.seed(66)
np.random.shuffle(x_data)
np.random.seed(66)
np.random.shuffle(y_data)
tf.random.set_seed(66)
# seed相同保证了shuffle过后x和y仍然一一对应

In [11]:
# 划分数据集
x_train = x_data[:-30]
y_train = y_data[:-30]
x_test = x_data[-30:]
y_test = y_data[-30:]

In [12]:
x_train

array([[6.2, 2.9, 4.3, 1.3],
       [6.8, 2.8, 4.8, 1.4],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 3.8, 1.7, 0.3],
       [6.6, 2.9, 4.6, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.1, 3.5, 1.4, 0.2],
       [5.5, 4.2, 1.4, 0.2],
       [4.3, 3. , 1.1, 0.1],
       [7.2, 3. , 5.8, 1.6],
       [6.5, 3. , 5.5, 1.8],
       [6.9, 3.1, 5.1, 2.3],
       [5. , 3.3, 1.4, 0.2],
       [6. , 3. , 4.8, 1.8],
       [5.8, 2.7, 5.1, 1.9],
       [4.4, 2.9, 1.4, 0.2],
       [5.5, 2.4, 3.8, 1.1],
       [6.3, 2.5, 4.9, 1.5],
       [7.3, 2.9, 6.3, 1.8],
       [7.6, 3. , 6.6, 2.1],
       [5. , 3.6, 1.4, 0.2],
       [6.1, 2.8, 4.7, 1.2],
       [6.1, 2.9, 4.7, 1.4],
       [6.1, 3. , 4.9, 1.8],
       [5.6, 3. , 4.5, 1.5],
       [7.2, 3.6, 6.1, 2.5],
       [5.1, 3.8, 1.5, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [6.1, 2.6, 5.6, 1.4],
       [6.5, 3. , 5.2, 2. ],
       [5. , 3. , 1.6, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [6.3, 2.9, 5.6, 1.8],
       [5.1, 3.8, 1.6, 0.2],
       [5.4, 3

In [13]:
mm = MinMaxScaler()
mm.fit(x_train)
x_train = mm.transform(x_train)
x_test = mm.transform(x_test)

In [14]:
x_train

array([[0.52777778, 0.31818182, 0.55932203, 0.5       ],
       [0.69444444, 0.27272727, 0.6440678 , 0.54166667],
       [0.61111111, 0.27272727, 0.61016949, 0.58333333],
       [0.38888889, 0.72727273, 0.11864407, 0.08333333],
       [0.63888889, 0.31818182, 0.61016949, 0.5       ],
       [0.38888889, 0.36363636, 0.54237288, 0.45833333],
       [0.22222222, 0.59090909, 0.06779661, 0.04166667],
       [0.33333333, 0.90909091, 0.06779661, 0.04166667],
       [0.        , 0.36363636, 0.01694915, 0.        ],
       [0.80555556, 0.36363636, 0.81355932, 0.625     ],
       [0.61111111, 0.36363636, 0.76271186, 0.70833333],
       [0.72222222, 0.40909091, 0.69491525, 0.91666667],
       [0.19444444, 0.5       , 0.06779661, 0.04166667],
       [0.47222222, 0.36363636, 0.6440678 , 0.70833333],
       [0.41666667, 0.22727273, 0.69491525, 0.75      ],
       [0.02777778, 0.31818182, 0.06779661, 0.04166667],
       [0.33333333, 0.09090909, 0.47457627, 0.41666667],
       [0.55555556, 0.13636364,

In [20]:
y_train

array([1, 1, 1, 0, 1, 1, 0, 0, 0, 2, 2, 2, 0, 2, 2, 0, 1, 1, 2, 2, 0, 1,
       1, 2, 1, 2, 0, 0, 2, 2, 0, 0, 2, 0, 1, 0, 1, 0, 1, 1, 0, 1, 2, 1,
       1, 1, 0, 1, 1, 2, 2, 0, 2, 2, 2, 2, 0, 2, 0, 2, 0, 0, 2, 0, 0, 2,
       1, 0, 0, 2, 2, 0, 0, 2, 0, 1, 1, 1, 2, 0, 0, 2, 2, 2, 1, 1, 1, 0,
       1, 1, 2, 0, 2, 0, 1, 0, 2, 1, 1, 2, 2, 1, 1, 0, 2, 1, 1, 0, 2, 2,
       0, 1, 1, 2, 2, 1, 1, 0, 2, 1])

In [15]:
train_dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train)).batch(32)
test_dataset = tf.data.Dataset.from_tensor_slices((x_test, y_test)).batch(32)

In [21]:
for step, (x,y) in enumerate(train_dataset):
    print(x.shape)
    print(y.shape)
    break

(32, 4)
(32,)


In [41]:
w1 = tf.Variable(tf.random.truncated_normal([4, 3], stddev=0.1, dtype=tf.float64), dtype=tf.float64)
b1 = tf.Variable(tf.random.truncated_normal([3], stddev=0.1, dtype=tf.float64), dtype=tf.float64)
# 就是一个y = w1*x + b1的拟合 x维度是[batch, feature = 4]
# 与w运算之后为[batch, 3]

In [47]:
EPOCH = 500
LR = 0.1
train_loss_results = list()
test_acc = list()
total_loss = 0.0

In [48]:
for epoch in range(EPOCH):
    total_loss = 0.0
    for step, (x, y) in enumerate(train_dataset):
        with tf.GradientTape() as tape:
            y_pred = tf.matmul(x, w1) + b1
            y_pred_prob = tf.nn.softmax(y_pred)
            y_one_hot = tf.one_hot(y, depth=3, dtype=tf.float64)
            loss = tf.reduce_mean(tf.square(y_one_hot - y_pred_prob))
            total_loss = total_loss + loss.numpy()

        grads = tape.gradient(loss, [w1, b1])
        # 求梯度
        w1.assign_sub(LR * grads[0])
        b1.assign_sub(LR * grads[1])
        # 更新参数
    print('epoch: {}, loss: {}'.format(epoch, total_loss))

epoch: 343, loss: 0.7205855410507238
epoch: 344, loss: 0.7203114857798766
epoch: 345, loss: 0.7200376320278203
epoch: 346, loss: 0.7197639799385656
epoch: 347, loss: 0.7194905296561316
epoch: 348, loss: 0.7192172813245205
epoch: 349, loss: 0.7189442350876963
epoch: 350, loss: 0.7186713910895624
epoch: 351, loss: 0.7183987494739387
epoch: 352, loss: 0.7181263103845414
epoch: 353, loss: 0.7178540739649603
epoch: 354, loss: 0.7175820403586384
epoch: 355, loss: 0.7173102097088513
epoch: 356, loss: 0.7170385821586862
epoch: 357, loss: 0.7167671578510222
epoch: 358, loss: 0.7164959369285099
epoch: 359, loss: 0.716224919533552
epoch: 360, loss: 0.7159541058082848
epoch: 361, loss: 0.7156834958945574
epoch: 362, loss: 0.7154130899339141
epoch: 363, loss: 0.7151428880675762
epoch: 364, loss: 0.7148728904364228
epoch: 365, loss: 0.7146030971809734
epoch: 366, loss: 0.71433350844137
epoch: 367, loss: 0.7140641243573599
epoch: 368, loss: 0.7137949450682785
epoch: 369, loss: 0.7135259707130316
epoc

In [50]:
total_correct = 0
total_num = 0
for x_test, y_test in test_dataset:
    y = tf.matmul(x_test, w1) + b1
    y = tf.nn.softmax(y)
    pred = tf.argmax(y, axis=1)
    pred = tf.cast(pred, dtype=y_test.dtype)
    correct = tf.equal(pred, y_test)
    correct = tf.cast(correct, dtype=tf.int32)
    correct = tf.reduce_sum(correct)
    total_correct = total_correct + int(correct)
    total_num = total_num + x_test.shape[0]

acc = total_correct / total_num
print(acc)

0.9333333333333333
