# tf常用函数
1. tf.constant直接创建一个张量
2. tf.convert_to_tensor直接从numpy转为tf
3. tf.zeros  tf.ones  tf.fill直接创建tensor
4. tf.random.normal生成正态分布的随机数 tf.random.truncated_normal生成截断正态分布
5. tf.cast强制tensor转换数据类型 tf.reduce_min计算张量维度上元素最小值 tf.reduce_max计算张量维度上元素最大值
6. tf.op op有一些基本的数学运算 add subtract multiply divide square pow sqrt matmul 矩阵乘法
7. tf.Variable 将变量标记为可训练的 会在反向传播中纪录梯度信息 with tf.GradientTape as tape + tape.gradient结构 可以对一系列运算过程进行求梯度
8. tf.one_hot one-hot根据取值映射为索引 对该索引位置置为1 其他部分置为0
9. tf.argmax 返回某维度上最大值的索引

In [27]:
import tensorflow as tf
import os
import numpy as np
os.environ['CUDA_VISIBLE_DEVICES'] = '1' # 使用 GPU 1

In [18]:
# tf.constant直接创建一个张量
a = tf.constant([1,5], dtype=tf.int64)
print(a)
print(a.shape)
print(a.dtype)
a

tf.Tensor([1 5], shape=(2,), dtype=int64)
(2,)
<dtype: 'int64'>


<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 5])>

In [19]:
# convert_to_tensor直接从numpy转为tf
a_np = np.random.randint(low = 0, high=10, size=(2,3))
a_tensor = tf.convert_to_tensor(a_np, dtype=tf.int64)
print(type(a_tensor))
print(a_tensor)
a_tensor

<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(
[[0 8 5]
 [8 7 5]], shape=(2, 3), dtype=int64)


<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[0, 8, 5],
       [8, 7, 5]])>

In [20]:
# tf.zeros  tf.ones  tf.fill都可以直接创建tensor
b = tf.zeros((3,2))
print(b)
c = tf.ones((2,5))
print(c)
d = tf.fill((1,3),5)
print(d)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], shape=(2, 5), dtype=float32)
tf.Tensor([[5 5 5]], shape=(1, 3), dtype=int32)


In [21]:
# tf.random.normal生成正态分布的随机数 tf.random.truncated_normal生成截断正态分布 能把正态分布的值限制在二倍标准差内
# tf.random.uniform生成均匀分布的随机数
e = tf.random.normal((3,2))
print(e)
f = tf.random.truncated_normal((2,3))
print(f)
g = tf.random.uniform((3,3),0,10)
print(g)

tf.Tensor(
[[ 0.5992623   0.19809349]
 [-1.2651374   0.58489203]
 [-3.0886664  -1.4638785 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[-0.60741556  0.15623452  0.2989469 ]
 [-0.8096293  -0.76912254 -0.09063936]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[7.4545097  3.932078   4.3188677 ]
 [3.05964    1.1418569  2.958293  ]
 [0.48840642 2.9316854  0.7476938 ]], shape=(3, 3), dtype=float32)


In [22]:
# tf.cast强制tensor转换数据类型 tf.reduce_min计算张量维度上元素最小值 tf.reduce_max计算张量维度上元素最大值
x1 = tf.constant([2,3,4], dtype=tf.int64)
x1_float = tf.cast(x1,dtype=tf.float32)
print(x1_float)
print(tf.reduce_min(x1))
print(tf.reduce_max(x1))

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)


In [23]:
# tf.reduce_op代表对tensor进行op操作
x2 = tf.random.normal((3,2))
print(x2)                          # x2 是[shape1, shape2] 那么 axis = 0 操作就是在shape1操作 变成[, shape2] axis = 1 操作就是对shape2操作变成[shape1, ]
print(tf.reduce_mean(x2, axis=1)) # axis = 1 代表在横向进行操作 保留第一维 所以是横向操作
print(tf.reduce_sum(x2, axis=0)) # axis = 0 代表在纵向进行操作 保留第二维 所以是纵向操作
print(tf.reduce_sum(x2))        # 不指定axis 代表对所有元素操作

tf.Tensor(
[[-0.5238342  -1.5508617 ]
 [ 0.04858428 -0.38857266]
 [-0.38953766 -0.00669476]], shape=(3, 2), dtype=float32)
tf.Tensor([-1.037348   -0.16999419 -0.19811621], shape=(3,), dtype=float32)
tf.Tensor([-0.8647876 -1.9461292], shape=(2,), dtype=float32)
tf.Tensor(-2.810917, shape=(), dtype=float32)


In [24]:
# tf.Variable 将变量标记为可训练的 会在反向传播中纪录梯度信息
# 这样就可以在反向传播中梯度下降更新了
w = tf.Variable(tf.random.normal((3,2)))

In [25]:
# tf.op op有一些基本的数学运算 add subtract multiply divide  维度相同的张量能进行四则运算
# square pow sqrt
# matmul 矩阵乘法

a = tf.ones([3,2])
b = tf.fill([2,5], 3.)
print(tf.matmul(a, b))

tf.Tensor(
[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]], shape=(3, 5), dtype=float32)


In [26]:
# tf.data.Dataset.from_tensor_slices((feature, labels))
features = tf.constant([12,23,10,17])
labels = tf.constant([0,1,0,1])
dataset = tf.data.Dataset.from_tensor_slices((features, labels))
print(dataset)
for element in dataset:
    print(element)

<TensorSliceDataset element_spec=(TensorSpec(shape=(), dtype=tf.int32, name=None), TensorSpec(shape=(), dtype=tf.int32, name=None))>
(<tf.Tensor: shape=(), dtype=int32, numpy=12>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)
(<tf.Tensor: shape=(), dtype=int32, numpy=23>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(), dtype=int32, numpy=10>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)
(<tf.Tensor: shape=(), dtype=int32, numpy=17>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)


In [29]:
# with tf.GradientTape as tape + tape.gradient结构 可以对一系列运算过程进行求梯度
with tf.GradientTape() as tape:
    w = tf.Variable(tf.constant(3.0))
    w = tf.add(w,tf.Variable(tf.constant(10.0)))
    loss = tf.pow(w,2)

grad = tape.gradient(loss,w) # tape.gradient求target对source的导数
print(grad)

tf.Tensor(26.0, shape=(), dtype=float32)


In [32]:
# tf.one_hot one-hot根据取值映射为索引 对该索引位置置为1 其他部分置为0
labels = tf.constant([1,0,2,-1,5])
output = tf.one_hot(labels,depth=5)
print(output)
# 默认axis = -1 则输出的维度是 (len(indices), depth)
# depth代表了可取的下标范围[0,..., depth-1]

tf.Tensor(
[[0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], shape=(5, 5), dtype=float32)


In [33]:
# tf.nn.softmax
score = tf.constant([2.31, 1.53, 3.43])
prob = tf.nn.softmax(score)
print(prob)

tf.Tensor([0.22107945 0.10134416 0.67757636], shape=(3,), dtype=float32)


In [34]:
# tf.assign_sub(自减值)
w = tf.Variable(4)
w.assign_sub(1)
print(w)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=3>


In [35]:
# tf.argmax 返回某维度上最大值的索引
test_mat = tf.constant([[1,2,3], [2,3,4], [2,3,5], [10,11,12]])
print(test_mat.shape)
# [batch, feature]
print(tf.argmax(input = test_mat, axis = 0))
print(tf.argmax(input=test_mat, axis=1))
# axis = 1就是feature维 在feature维进行argmax feature维度消失 其他维度不变

(4, 3)
tf.Tensor([3 3 3], shape=(3,), dtype=int64)
tf.Tensor([2 2 2 2], shape=(4,), dtype=int64)
